// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __TimedNavdata_hh__
#define __TimedNavdata_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_TimedNavdata
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_TimedNavdata
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_TimedNavdata
#endif



#ifndef __BasicDataType_hh_EXTERNAL_GUARD__
#define __BasicDataType_hh_EXTERNAL_GUARD__
#include <BasicDataType.hh>
#endif
#ifndef __ExtendedDataTypes_hh_EXTERNAL_GUARD__
#define __ExtendedDataTypes_hh_EXTERNAL_GUARD__
#include <ExtendedDataTypes.hh>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE naistrobotics

_CORBA_MODULE_BEG

  struct TimedNavdata {
    typedef _CORBA_ConstrType_Variable_Var<TimedNavdata> _var_type;

    
    RTC::Time tm;

    ::CORBA::Long imgwidth;

    ::CORBA::Long imgheight;

    ::CORBA::Long imgSize;

    ::CORBA::Long imgType;

    RTC::TimedOctetSeq imgData;

    ::CORBA::Double roll;

    ::CORBA::Double pitch;

    ::CORBA::Double yaw;

    ::CORBA::Double altitude;

    ::CORBA::Double vx;

    ::CORBA::Double vy;

    ::CORBA::Double vz;

    ::CORBA::Short battery;

    ::CORBA::Boolean onground;

    RTC::TimedDoubleSeq additional;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef TimedNavdata::_var_type TimedNavdata_var;

  typedef _CORBA_ConstrType_Variable_OUT_arg< TimedNavdata,TimedNavdata_var > TimedNavdata_out;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_TimedNavdata;

_CORBA_MODULE_END



_CORBA_MODULE POA_naistrobotics
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_naistrobotics
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

extern void operator<<=(::CORBA::Any& _a, const naistrobotics::TimedNavdata& _s);
extern void operator<<=(::CORBA::Any& _a, naistrobotics::TimedNavdata* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, naistrobotics::TimedNavdata*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const naistrobotics::TimedNavdata*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_TimedNavdata
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_TimedNavdata
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_TimedNavdata
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_TimedNavdata
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_TimedNavdata
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_TimedNavdata
#endif

#endif  // __TimedNavdata_hh__

