// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __TimedControldata_hh__
#define __TimedControldata_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_TimedControldata
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_TimedControldata
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_TimedControldata
#endif



#ifndef __BasicDataType_hh_EXTERNAL_GUARD__
#define __BasicDataType_hh_EXTERNAL_GUARD__
#include <BasicDataType.hh>
#endif
#ifndef __ExtendedDataTypes_hh_EXTERNAL_GUARD__
#define __ExtendedDataTypes_hh_EXTERNAL_GUARD__
#include <ExtendedDataTypes.hh>
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE naistrobotics

_CORBA_MODULE_BEG

  struct TimedControldata {
    typedef _CORBA_ConstrType_Fix_Var<TimedControldata> _var_type;

    
    RTC::Time tm;

    ::CORBA::Double yaw;

    ::CORBA::Double vx;

    ::CORBA::Double vy;

    ::CORBA::Double vz;

    ::CORBA::Boolean onground;

  

    void operator>>= (cdrStream &) const;
    void operator<<= (cdrStream &);
  };

  typedef TimedControldata::_var_type TimedControldata_var;

  typedef TimedControldata& TimedControldata_out;

  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_TimedControldata;

_CORBA_MODULE_END



_CORBA_MODULE POA_naistrobotics
_CORBA_MODULE_BEG

_CORBA_MODULE_END



_CORBA_MODULE OBV_naistrobotics
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

extern void operator<<=(::CORBA::Any& _a, const naistrobotics::TimedControldata& _s);
extern void operator<<=(::CORBA::Any& _a, naistrobotics::TimedControldata* _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, naistrobotics::TimedControldata*& _sp);
extern _CORBA_Boolean operator>>=(const ::CORBA::Any& _a, const naistrobotics::TimedControldata*& _sp);





#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_TimedControldata
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_TimedControldata
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_TimedControldata
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_TimedControldata
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_TimedControldata
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_TimedControldata
#endif

#endif  // __TimedControldata_hh__

