// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "TimedControldata.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



void
naistrobotics::TimedControldata::operator>>= (cdrStream &_n) const
{
  (const RTC::Time&) tm >>= _n;
  yaw >>= _n;
  vx >>= _n;
  vy >>= _n;
  vz >>= _n;
  _n.marshalBoolean(onground);

}

void
naistrobotics::TimedControldata::operator<<= (cdrStream &_n)
{
  (RTC::Time&)tm <<= _n;
  (::CORBA::Double&)yaw <<= _n;
  (::CORBA::Double&)vx <<= _n;
  (::CORBA::Double&)vy <<= _n;
  (::CORBA::Double&)vz <<= _n;
  onground = _n.unmarshalBoolean();

}

