// This file is generated by omniidl (C++ backend) - omniORB_4_1. Do not edit.

#include "TimedNavdata.hh"

OMNI_USING_NAMESPACE(omni)

static const char* _0RL_dyn_library_version = omniORB_4_1_dyn;

static ::CORBA::TypeCode::_Tracker _0RL_tcTrack(__FILE__);

static CORBA::PR_structMember _0RL_structmember_RTC_mTime[] = {
  {"sec", CORBA::TypeCode::PR_ulong_tc()},
  {"nsec", CORBA::TypeCode::PR_ulong_tc()}
};

#ifdef _0RL_tc_RTC_mTime
#  undef _0RL_tc_RTC_mTime
#endif
static CORBA::TypeCode_ptr _0RL_tc_RTC_mTime = CORBA::TypeCode::PR_struct_tc("IDL:RTC/Time:1.0", "Time", _0RL_structmember_RTC_mTime, 2, &_0RL_tcTrack);


static CORBA::PR_structMember _0RL_structmember_RTC_mTimedOctetSeq[] = {
  {"tm", _0RL_tc_RTC_mTime},
  {"data", CORBA::TypeCode::PR_sequence_tc(0, CORBA::TypeCode::PR_octet_tc(), &_0RL_tcTrack)}
};

#ifdef _0RL_tc_RTC_mTimedOctetSeq
#  undef _0RL_tc_RTC_mTimedOctetSeq
#endif
static CORBA::TypeCode_ptr _0RL_tc_RTC_mTimedOctetSeq = CORBA::TypeCode::PR_struct_tc("IDL:RTC/TimedOctetSeq:1.0", "TimedOctetSeq", _0RL_structmember_RTC_mTimedOctetSeq, 2, &_0RL_tcTrack);


static CORBA::PR_structMember _0RL_structmember_RTC_mTimedDoubleSeq[] = {
  {"tm", _0RL_tc_RTC_mTime},
  {"data", CORBA::TypeCode::PR_sequence_tc(0, CORBA::TypeCode::PR_double_tc(), &_0RL_tcTrack)}
};

#ifdef _0RL_tc_RTC_mTimedDoubleSeq
#  undef _0RL_tc_RTC_mTimedDoubleSeq
#endif
static CORBA::TypeCode_ptr _0RL_tc_RTC_mTimedDoubleSeq = CORBA::TypeCode::PR_struct_tc("IDL:RTC/TimedDoubleSeq:1.0", "TimedDoubleSeq", _0RL_structmember_RTC_mTimedDoubleSeq, 2, &_0RL_tcTrack);

static CORBA::PR_structMember _0RL_structmember_naistrobotics_mTimedNavdata[] = {
  {"tm", _0RL_tc_RTC_mTime},
  {"imgwidth", CORBA::TypeCode::PR_long_tc()},
  {"imgheight", CORBA::TypeCode::PR_long_tc()},
  {"imgSize", CORBA::TypeCode::PR_long_tc()},
  {"imgType", CORBA::TypeCode::PR_long_tc()},
  {"imgData", _0RL_tc_RTC_mTimedOctetSeq},
  {"roll", CORBA::TypeCode::PR_double_tc()},
  {"pitch", CORBA::TypeCode::PR_double_tc()},
  {"yaw", CORBA::TypeCode::PR_double_tc()},
  {"altitude", CORBA::TypeCode::PR_double_tc()},
  {"vx", CORBA::TypeCode::PR_double_tc()},
  {"vy", CORBA::TypeCode::PR_double_tc()},
  {"vz", CORBA::TypeCode::PR_double_tc()},
  {"battery", CORBA::TypeCode::PR_short_tc()},
  {"onground", CORBA::TypeCode::PR_boolean_tc()},
  {"additional", _0RL_tc_RTC_mTimedDoubleSeq}
};

#ifdef _0RL_tc_naistrobotics_mTimedNavdata
#  undef _0RL_tc_naistrobotics_mTimedNavdata
#endif
static CORBA::TypeCode_ptr _0RL_tc_naistrobotics_mTimedNavdata = CORBA::TypeCode::PR_struct_tc("IDL:naistrobotics/TimedNavdata:1.0", "TimedNavdata", _0RL_structmember_naistrobotics_mTimedNavdata, 16, &_0RL_tcTrack);






#if defined(HAS_Cplusplus_Namespace) && defined(_MSC_VER)
// MSVC++ does not give the constant external linkage otherwise.
namespace naistrobotics { 
  const ::CORBA::TypeCode_ptr _tc_TimedNavdata = _0RL_tc_naistrobotics_mTimedNavdata;
} 
#else
const ::CORBA::TypeCode_ptr naistrobotics::_tc_TimedNavdata = _0RL_tc_naistrobotics_mTimedNavdata;
#endif


static void _0RL_naistrobotics_mTimedNavdata_marshal_fn(cdrStream& _s, void* _v)
{
  naistrobotics::TimedNavdata* _p = (naistrobotics::TimedNavdata*)_v;
  *_p >>= _s;
}
static void _0RL_naistrobotics_mTimedNavdata_unmarshal_fn(cdrStream& _s, void*& _v)
{
  naistrobotics::TimedNavdata* _p = new naistrobotics::TimedNavdata;
  *_p <<= _s;
  _v = _p;
}
static void _0RL_naistrobotics_mTimedNavdata_destructor_fn(void* _v)
{
  naistrobotics::TimedNavdata* _p = (naistrobotics::TimedNavdata*)_v;
  delete _p;
}

void operator<<=(::CORBA::Any& _a, const naistrobotics::TimedNavdata& _s)
{
  naistrobotics::TimedNavdata* _p = new naistrobotics::TimedNavdata(_s);
  _a.PR_insert(_0RL_tc_naistrobotics_mTimedNavdata,
               _0RL_naistrobotics_mTimedNavdata_marshal_fn,
               _0RL_naistrobotics_mTimedNavdata_destructor_fn,
               _p);
}
void operator<<=(::CORBA::Any& _a, naistrobotics::TimedNavdata* _sp)
{
  _a.PR_insert(_0RL_tc_naistrobotics_mTimedNavdata,
               _0RL_naistrobotics_mTimedNavdata_marshal_fn,
               _0RL_naistrobotics_mTimedNavdata_destructor_fn,
               _sp);
}

::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, naistrobotics::TimedNavdata*& _sp)
{
  return _a >>= (const naistrobotics::TimedNavdata*&) _sp;
}
::CORBA::Boolean operator>>=(const ::CORBA::Any& _a, const naistrobotics::TimedNavdata*& _sp)
{
  void* _v;
  if (_a.PR_extract(_0RL_tc_naistrobotics_mTimedNavdata,
                    _0RL_naistrobotics_mTimedNavdata_unmarshal_fn,
                    _0RL_naistrobotics_mTimedNavdata_marshal_fn,
                    _0RL_naistrobotics_mTimedNavdata_destructor_fn,
                    _v)) {
    _sp = (const naistrobotics::TimedNavdata*)_v;
    return 1;
  }
  return 0;
}

